### ISSUE TITLE
Lighter Icons

### ISSUE THREAD

**Issue by SoloReverse** [marcbruederlin/vscode-next-icons#1]
The icons are really beautiful and help a lot in quickly managing the folders. I tend to use a dark theme, but not as dark that the icons become visible. The contrast difference isn't that high.

Would you mind setting up a white set of icons?
I could do it but just let me know how you'd like them named and where and I could create a PR.

**Comment by marcbruederlin** [comment]
Hey @SoloReverse,

thank you for reaching out. I’ve just published an update that includes a variant for light and dark icons, which you can now choose manually. Please let me know if this works for you.

**Comment by SoloReverse** [comment]
Works beautifully. Thanks @marcbruederlin.
